### ISSUE TITLE
ورژن 14

### ISSUE THREAD

**Issue by amirnano** [parodoo/parOdoo#5]
سلام اول از همه میخواستم تشکر کنم بابت انتشار این ماژول و رویکرد اپن سورسی که دارید واقعا قابل ستایش هست.
من این ماژول رو نصب کردم روی ورژن 14 اما به علت بهم نخوردن کدهای اصلی پوشه ادان رو جایگزین فایل های اصلی نکردم.  اما ماژول کار کرد و بیشتر قسمت ها به شمسی تغییر پیدا کرد ، میخواستم بپرسم از خدمت شما آیا امکان داره ماژول به صورت یک ماژول مجزا بدون نیاز به جایگذاری فایل های قبلی و اصلی توسعه پیدا کنه یا خیر؟

**Comment by BabakMahmoudi** [comment]
سلام. داریم روی این مشکل کار میکنیم. خبر میدم.

**Comment by BabakMahmoudi** [comment]
There's a conflict between Odoo locale and moment-jalali. The new version uses Persian digits for dates when the user selects Persian language, while in moment-jalali its an option that should be set. We decided to disable digit conversions in Odoo locale since its a bit awkward to have Persian digits in dates, while everywhere else we see Latin digits. To disable digit conversions in Odoo, one should edit 'fa.js' this is located in server\odoo\addons\web\static\lib\moment\locale folder, like:
`/*
    * parOdoo: To avoid persin digit conflicts with moment-jajali
    * digit conversions are disabled

    preparse: function (string) {
        return string.replace(/[۰-۹]/g, function (match) {
            return numberMap[match];
        }).replace(/،/g, ',');
    },
    postformat: function (string) {
        return string.replace(/\d/g, function (match) {
            return symbolMap[match];
        }).replace(/,/g, '،');
    },
    */
    ordinalParse: /\d{1,2}م/,`

This will disable digit conversions. We have included 'fa.js' in the root of repository.
See this [link ](https://www.gnco.ir/%d9%be%d8%a7%d8%b1%d8%a7%d8%af%d9%88-%d9%85%d8%b4%da%a9%d9%84-%d8%aa%d9%82%d9%88%db%8c%d9%85-%d8%b4%d9%85%d8%b3%db%8c-%d8%af%d8%b1-%d8%a7%d9%8f%d8%af%d9%88-14/)for more details in Persian.

**Comment by BabakMahmoudi** [comment]
Fixed with disabling Persian digit conversions.
